version: "3.1"
services:

  web:
    container_name: espresso-web-tester
    hostname: espresso-web-test
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./app.py:/home/anaconda/app.py
    ports:
        - 5000:5000
    depends_on:
      - db
      - maria_db


  db:
    image: postgres:10-alpine
    container_name: espresso-db-test
    hostname: espresso-db
    volumes:
         - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: something
      POSTGRES_DB: espresso


  maria_db:
    image: mariadb
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: something

  admin:
    image: adminer
    container_name: espresso-db-client-test
    hostname: espresso-db-client
    depends_on:
      - db
      - maria_db
    ports:
      - 8080:8080

volumes: 
  pgdata:
